//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quan_Ly_Diem_Thi.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class DiemThi
    {
        [Required]
        [Key]
        [Column (Order = 0)]
        public int IdHocVien { get; set; }
        [Key]
        [Column(Order = 1)]
        [Required]
        public int IdMonHoc { get; set; }
        [Key]
        [Column(Order = 2)]
        [Required]
        [Range(1,10)]
        public int LanThi { get; set; }
        [Required]
        [Display(Name = "Điểm Thi ")]
        [Range(1,100)]
        public int DiemThi1 { get; set; }
    
        public virtual HocVien HocVien { get; set; }
        public virtual MonHoc MonHoc { get; set; }
    }
}
