//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Car_Mg_MVC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Car
    {
        public int CarId { get; set; }
        [Required(ErrorMessage = "Bắt buộc phải nhập dữ liệu {0}")]
        [StringLength(150 , MinimumLength = 2)]
        [Display(Name ="Dòng xe")]
        public string CarModel { get; set; }
        [Required]
        [Range(1970,2020,ErrorMessage = "Dữ liệu năm sản xuất phải từ {1} đến {2}")]
        public string CarModelYear { get; set; }
        [RegularExpression("ST\\d{10}")]
        public string CarVIN { get; set; }
        public Nullable<int> CarMakerID { get; set; }
    
        public virtual Maker Maker { get; set; }
    }
}
