//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Console_API_Oin_Product.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cart
    {
        public int ProId { get; set; }
        public Nullable<int> ProPrice { get; set; }
        public Nullable<int> ProQuantity { get; set; }
        public int BillId { get; set; }
    
        public virtual Bill Bill { get; set; }
        public virtual Product Product { get; set; }
    }
}
