//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_Car.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Car
    {
        public int CarId { get; set; }
        public string CarModer { get; set; }
        public string CarModelYear { get; set; }
        public string CarVin { get; set; }
        public Nullable<int> IdMakerCar { get; set; }
    
        public virtual MOCK_DATA MOCK_DATA { get; set; }
    }
}
