//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Form_ET_dathang_HGK
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderProduct
    {
        public int ProductId { get; set; }
        public int OrderId { get; set; }
        public int Quantity { get; set; }
        public int Price { get; set; }
        public int Total { get { return Quantity * Price; } }
       // public string ProductName { get { return Product.Name; } }
        public virtual Order Order { get; set; }
        public virtual Product Product { get; set; }
    }
}
